
server:
  port: 8000

###起个名字作为服务名称(该服务注册到eureka注册中心的名称，比如商品服务)
spring:
  application:
    name: xc-design #服务名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://134.175.244.202:3308/design
    username: root
    password: 123456

#  data:
#    elasticsearch:
#      cluster-name: es
#      cluster-nodes: 192.168.0.101:9300

#  kafka:
#    #集群地址
#    bootstrap-servers: 134.175.244.202:9092,120.79.42.229:9092
#    consumer:
#      #知道默认的组名
#      group-id: kafka2
##      key-deserializer:
#    producer:
##      批量抓取
#      batch-size: 65536
#      #缓存容量
#      buffer-memory: 524288
#      bootstrap-servers: 134.175.244.202:9092,120.79.42.229:9092



###服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      #      defaultZone: http://120.79.42.229:7777/eureka/,http://120.79.42.229:8888/eureka/,http://120.79.42.229:9999/eureka/
      defaultZone: http://127.0.0.1:10000/eureka/
    ###因为该应用为服务提供者，是eureka的一个客户端，需要注册到注册中心
    register-with-eureka: true
    ###是否需要从eureka上检索服务
    fetch-registry: true
  instance:
    #设置使用IP
    prefer-ip-address: true
    #设置外网IP号
    ip-address: 127.0.0.1   #134.175.244.202
    #设置外网端口号
    non-secure-port: 8000
#    hostname: 127.0.0.1

